import type { Metadata } from 'next'
import { Figtree, Lora } from 'next/font/google'
import '@/app/ui/globals.css'
import { ThemeProvider } from '@/app/ui/theme-provider'
import { ClerkProvider } from '@clerk/nextjs'
import { Header } from '@/app/ui/header'
import { Footer } from '@/app/ui/footer'
import { Toaster } from '@/components/ui/sonner'
import { getDictionary, getClerkLocalization } from '@/lib/dictionary'
import { type Locale, generateStaticParams } from '@/i18n-config'

const fontSans = Figtree({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-sans',
})

const fontSerif = Lora({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-serif',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// 确保根布局也导出了 generateStaticParams
export { generateStaticParams }

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: Promise<{ lang: Locale }>
}) {
  // 在服务端获取所有需要的国际化资源
  const { lang } = await params
  const dictionary = await getDictionary(lang)
  const clerkLocalization = getClerkLocalization(lang)

  return (
    <ClerkProvider localization={{ ...clerkLocalization, ...dictionary.clerk }}>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${fontSans.variable} ${fontSerif.variable} font-sans min-h-screen w-full bg-background text-foreground antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="relative flex flex-col min-h-screen w-full">
              <Header lang={lang} dictionary={dictionary} />
              <main className="flex-1 w-full">{children}</main>
              <Footer dictionary={dictionary} />
            </div>
            <Toaster richColors />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
