import type { Metadata } from 'next'
import { Figtree, Lora } from 'next/font/google'
import '@/app/ui/globals.css'
import { ThemeProvider } from '@/components/ui/theme-provider'
import { ClerkProvider } from '@clerk/nextjs'
import { Header } from '@/components/ui/header'
import { Toaster } from '@/components/ui/sonner'
import { type Locale } from '@/i18n-config'
import { getDictionary, getClerkLocalization } from '@/lib/dictionary'

const fontSans = Figtree({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-sans',
})

const fontSerif = Lora({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-serif',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: Promise<{ lang: Locale }>
}) {
  // 在服务端获取所有需要的国际化资源
  const { lang } = await params
  const dictionary = await getDictionary(lang)
  const clerkLocalization = getClerkLocalization(lang)

  return (
    <ClerkProvider localization={{ ...clerkLocalization, ...dictionary.clerk }}>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${fontSans.variable} ${fontSerif.variable} font-sans min-h-screen bg-background text-foreground antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex flex-col min-h-screen">
              {/* 2. 在这里直接使用 Header，干净利落 */}
              <Header />

              <main className="flex-grow">{children}</main>

              {/* 预留 Footer 的位置 */}
              {/* <Footer /> */}
            </div>
            <Toaster richColors />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
